"use client";

import { Button } from "@/components/ui/button";
import { ChevronDown } from "lucide-react";

export function HeroContent() {
  const handleScrollToContent = () => {
    const element = document.getElementById("ai-generation-engine");
    if (element) {
      element.scrollIntoView({
        behavior: "smooth",
        block: "start",
      });
    }
  };

  return (
    <div className="flex-1 flex items-center justify-center px-4 sm:px-6 lg:px-8">
      <div className="text-center max-w-4xl mx-auto">
        {/* Main Title */}
        <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-foreground mb-6">
          Hello, I'm generated by AI
        </h1>

        {/* Context Text */}
        <p className="text-lg sm:text-xl text-muted-foreground mb-12 max-w-2xl mx-auto leading-relaxed">
          This page and its structure were dynamically generated by an LLM
          following patterns and components sourced from the shadcn/ui component
          library.
        </p>

        {/* Scroll Button */}
        <Button
          onClick={handleScrollToContent}
          size="lg"
          className="px-8 py-3 text-lg"
          aria-label="Scroll to learn more about AI generation"
        >
          Learn More
          <ChevronDown className="ml-2 h-5 w-5" />
        </Button>
      </div>
    </div>
  );
}
